PROJECTO_TLP/PROJECTO_TLP/Models/login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MySql.Data.MySqlClient;

namespace PROJECTO_TLP.Models
{
    public class login : Conector
    {
        public bool VerificarUsuario(string email, string senha)
        {
            bool usuarioExiste = false;
            try
            {
                abrirconexao();

                string query = "SELECT COUNT(*) FROM user WHERE email = @Email AND palavra_passe = @Senha";
                MySqlCommand comando = new MySqlCommand(query, connexao);
                comando.Parameters.AddWithValue("@Email", email);
                comando.Parameters.AddWithValue("@Senha", senha);

                int count = Convert.ToInt32(comando.ExecuteScalar());

                if (count > 0)
                    usuarioExiste = true;
            }
            catch (Exception ex)
            {
               
                Console.WriteLine("Erro ao verificar usuário: " + ex.Message);
            }
            finally
            {
                fecharconexao();
            }

            return usuarioExiste;
        }
    }
}

PROJECTO_TLP/PROJECTO_TLP/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PROJECTO_TLP.App_Start.Controllers
{
    public class AdministradorController : Controller
    {
        // GET: Administrador
        public ActionResult PaginaInicial()
        {
            return View();
        }

        public ActionResult PaginaPublicadores()
        {
            return View();
        }

        public ActionResult PaginaDefinicoes()
        {
            return View();
        }
        public ActionResult PaginaAjuda()
        {
            return View();
        }


    }
}

PROJECTO_TLP/PROJECTO_TLP/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PROJECTO_TLP.App_Start.Controllers
{
    public class ContaController : Controller
    {
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        // GET: Conta
        public ActionResult Registro()
        {
            return View();
        }
        public ActionResult Registro2()
        {
            return View();
        }

        public ActionResult ConfirmarRegistro()
        {
            return View();
        }
    }
}

PROJECTO_TLP/PROJECTO_TLP/Controllers/RecuperarContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace PROJECTO_TLP.Controllers
{
    public class RecuperarContaController : Controller
    {
        // GET: EsqueceuPasse
        public ActionResult EsqueceuPasse()
        {
            return View();
        }

        

    }
}

PROJECTO_TLP/PROJECTO_TLP/Views/Conta/ConfirmarRegistro.cshtml
@{
    ViewBag.Title = "Confirmar Registro";
}

<style>
    #main-confirmar {
        margin: auto;
        padding: 2vh 2vh 5vh 2vh;
        background-color: #fff;
        max-width: 800px;
        box-shadow: 0 0 10px #dfdfdf;
    }

    .control-label {
        font-size: 2.2vh;
    }

    #aside {
        max-width: 800px;
        margin: auto;
        height: 250px;
        background-color: #d2d2fa;
        color: #404040;
        box-shadow: 0 0 2px silver;
        padding: 2vh 5vh;
        margin-bottom: 10px;
    }
</style>

<div>


    <main id="main-confirmar" class="container row">
        <aside id="aside" class="container row" role="complementary">
            <h1 style="font-size:40px">Congregação <span class="text-primary">Combal-18</span> </h1>
            <h1>Relatório de serviço de campo</h1>
        </aside>

        <h2>@ViewBag.Title</h2>
        <hr />

        <h3>Informacoes pessoais</h3>
        <div class="table-responsive">
            <table class=" table table-striped table-hover ">
                <thead>
                    <tr>
                        <th>Nome completo</th>
                        <th>Email</th>
                        <th>Palavra passe</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Fernando</td>
                        <td>afonso@gmail.com</td>
                        <td>12234356475</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <h3>Informacoes adicionais</h3>

        <div class="table-responsive">
            <table class=" table table-striped table-hover ">
                <thead>
                    <tr>
                        <th>Data de nascimento</th>
                        <th>Data de batismo</th>
                        <th>Anciao</th>
                        <th>Servo ministerial</th>
                        <th>Pioneiro ou missionario</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>22-02-2003</td>
                        <td>22-02-2003</td>
                        <td class="text-success">Sim</td>
                        <td class="text-danger"></td>
                        <td class="text-danger">Nao</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="btn-group col-md-6">
            <a style="height:40px;font-size:2.5vh" class="btn btn-success col-md-6" @Html.ActionLink("Confirmar", "ConfirmarRegistro", "Conta") </a>
            <a style="height:40px;font-size:2.5vh" class="btn btn-danger col-md-6" @Html.ActionLink("Cancelar", "Registro2", "Conta")  </a>
        </div>
    </main>


</div>

PROJECTO_TLP/PROJECTO_TLP/Views/Conta/Login.cshtml
@using PROJECTO_TLP.Models
@model LoginViewModel
@{
    ViewBag.Title = "Iniciar sessão";
}

<style>
    #main-login {
        margin: auto;
        padding: 2vh 2vh 5vh 2vh;
        background-color: #fff;
        max-width: 800px;
        box-shadow: 0 0 10px #dfdfdf;
    }

    .control-label {
        font-size: 2.2vh;
    }

    #aside {
        max-width: 800px;
        margin: auto;
        background-color: #cbd7fa;
        color: #404040;
        box-shadow: 0 0 2px silver;
        padding: 2vh 5vh 5vh 5vh;
        margin-bottom: 10px;
        display: flex;
        flex-direction: column;
        gap: 1.5rem;
    }

    #div-opcao {
        text-align: center;
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        column-gap: 1rem;
    }

    .btn-opcao {
        background: transparent;
        width: 45%;
        height: 50px;
        border: none;
        outline: none;
        text-decoration: none;
        font-size: 3vh;
        transition: 0.2s;
    }

        .btn-opcao:hover {
            transform: scale(1.1, 1.1);
            border: none;
            padding-bottom: 5px;
            /*border-bottom:3px solid;*/
        }

    a {
        text-decoration: none;
        border: none;
        outline: none;
        text-decoration-style: none;
        text-decoration-line: none;
    }

    /*validacao dos campos*/

    /*.form-control:valid{

     }
     .form-control:invalid{

     }*/

    .input-invalido {
        border: 1px solid red;
    }

        .input-invalido::after() {
            content: 'Campo invalido';
        }

    .input-valido {
        border: 1px solid #dedede;
    }

    .div-alerta {
        padding: 1rem;
        display: none;
    }
</style>


<div id="div-login">


    <main id="main-login" class="container row">
        <aside id="aside" class="container row" role="complementary">
            <h1 style="font-size:40px">Congregação <span class="text-primary">Combal-18</span> </h1>
            <h1>Relatório de serviço de campo</h1>


            <div id="div-opcao">
                <a class="btn-opcao text-primary" @Html.ActionLink("Criar conta", "registro", "conta") </a>
                <a class="btn-opcao text-primary" @Html.ActionLink("Iniciar sessao", "login", "conta") </a>
            </div>
        </aside>

        <h2>@ViewBag.Title.</h2>
        <hr />
        <div class="form-group row">
            <div class=" col-md-5"><label for="input-nome" class="control-label">Nome</label></div>
            <div class="col-md-7"><input onchange="validarCamposLogin" type="text" id="input-nome" class="form-control input-login" required /><div class="text-danger div-alerta">Campo invalido!!</div></div>
        </div>

        <div class="form-group row">
            <div class=" col-md-5"><label for="input-palavra-passe" class="control-label ">Palavra-passe</label></div>
            <div class="col-md-7"><input type="password" id="input-palavra-passe" class="form-control input-login" required /><div class="text-danger div-alerta">Campo invalido!!</div></div>
        </div>

        <div id="divTeste" style="display:flex;width:100%;column-gap:5vh;justify-content:flex-start;flex-wrap:wrap">
            @*<a class="btn btn-primary" role="button" asp-controller="EsqueceuPasse" asp-action="Index">Esqueceu a palavra-passe?</a>*@
            @*sintaxe:   @Html.ActionLink("texto do link", "a pagina","a pasta onde esta a pagina") *@
            @*sintaxe:   @Html.ActionLink("texto do link", "a accao/metodo","a controller") *@

            <div class="row col-md-offset-0" style="width:150%;padding:0 0 10px 0">
                <div class="col-md-12" style="font-size:2.5vh">
                    @Html.ActionLink("Esqueceu a palavra-passe?", "EsqueceuPasse", "RecuperarConta")
                </div>

            </div>


            <a id="btn-login" style="height:40px;font-size:2.5vh" class="btn col-md-6 btn-primary" @Html.ActionLink("Iniciar sessão", "PaginaInicial", "Administrador")</a>

        </div>
    </main>

</div>


@*<footer>
        <p>&copy; @DateTime.Now.Year - Congreg</p>
    </footer>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROJECTO_TLP/PROJECTO_TLP/Views/Conta/Registro.cshtml
@model PROJECTO_TLP.Models.RegisterViewModel
@{
    ViewBag.Title = "Criar nova conta";
}

<style>
    #link {
        color: white;
    }

    #div-registro {
        margin: auto;
        /*margin-top:1rem;*/
    }

    #main-registrar {
        margin: auto;
        padding: 2vh 2vh 5vh 2vh;
        background-color: #fff;
        max-width: 800px;
        box-shadow: 0 0 10px #dfdfdf;
    }

    .control-label {
        font-size: 2.2vh;
    }

    /*99b3f0    aabceb*/
    #aside {
        max-width: 800px;
        margin: auto;
        background-color: #cbd7fa;
        color: #404040;
        box-shadow: 0 0 2px silver;
        padding: 2vh 5vh 5vh 5vh;
        margin-bottom: 10px;
        display: flex;
        flex-direction: column;
        gap: 1.5rem;
    }

    #div-opcao {
        text-align: center;
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        column-gap: 1rem;
    }

    .btn-opcao {
        background: transparent;
        width: 45%;
        height: 50px;
        border: none;
        outline: none;
        text-decoration: none;
        font-size: 3vh;
        transition: 0.2s;
    }

        .btn-opcao:hover {
            transform: scale(1.1, 1.1);
            border: none;
            padding-bottom: 5px;
            /*border-bottom:3px solid;*/
        }

    a {
        text-decoration: none;
        border: none;
        outline: none;
        text-decoration-style: none;
        text-decoration-line: none;
    }

    /*vaalidaca com css*/
    /*.form-control:valid{
        border:1px solid #dedede;
    }
    .form-control:invalid{
        border:1px solid red;
    }*/


    .input-invalido {
        border: 1px solid red;
    }

        .input-invalido::after() {
            content: 'Campo invalido';
        }

    .input-valido {
        border: 1px solid #dedede;
    }

    .div-alerta {
        padding: 1rem;
        display: none;
    }
</style>

<div id="div-registro">


    <main id="main-registrar" class="container row">

        <aside id="aside" class="container row" role="complementary">
            <h1 style="font-size:40px">Congregação <span class="text-primary">Combal-18</span> </h1>
            <h1>Relatório de serviço de campo</h1>


            <div id="div-opcao">
                <a class="btn-opcao text-primary" @Html.ActionLink("Criar conta", "registro", "conta") </a>
                <a class="btn-opcao text-primary" @Html.ActionLink("Iniciar sessao", "login", "conta") </a>
            </div>
        </aside>
        <h2>@ViewBag.Title.</h2>
        <h3>Informacoes pessoais</h3>
        <hr />

        @Html.ValidationSummary("", new { @class = "text-danger" })



        <div class="form-group row">
            <div class=" col-md-5"><label for="div-nome" class="control-label">Nome completo</label></div>
            <div class="col-md-7"><input type="text" id="div-nome" class="form-control input-registro" required /><div class="text-danger div-alerta">Campo invalido!!</div></div>
        </div>

        <div class="form-group row">
            <div class=" col-md-5"><label for="div-email" class="control-label">Email</label></div>
            <div class="col-md-7"><input type="email" id="div-email" class="form-control input-registro" required /><div class="text-danger div-alerta">Campo invalido!!</div></div>
        </div>

        <div class="form-group row">
            <div class=" col-md-5"><label for="div-palavra-passe" class="control-label">Palavra-passe</label></div>
            <div class="col-md-7"><input type="password" id="div-palavra-passe" class="form-control input-registro" required /><div class="text-danger div-alerta">Campo invalido!!</div></div>
        </div>

        <div class="form-group row">
            <div class=" col-md-5"><label for="div-confirmar" class="control-label">Confirmar palavra-passe</label></div>
            <div class="col-md-7"><input type="password" id="div-confirmar" class="form-control input-registro col-md-9" required /><div class="text-danger div-alerta">Campo invalido!!</div></div>
        </div>


        <div style="display:flex;width:100%;column-gap:5vh;justify-content:flex-start;flex-wrap:wrap">
            <div class="row col-md-offset-0" style="width:150%;padding:0 0 10px 0">
                <div class="col-md-12" style="font-size:2.5vh">
                    Ja tenho uma conta. <a>@Html.ActionLink("Iniciar sessao", "Login", "Conta")</a>
                </div>

            </div>


            <a role="button" class="btn col-md-6 btn btn-primary" style="height:40px;font-size:2.5vh" @Html.ActionLink("Seguinte", "Registro2", "Conta")</a>

        </div>



    </main>

    @*<footer>
            <p>&copy; @DateTime.Now.Year - Congreg</p>
        </footer>*@
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROJECTO_TLP/PROJECTO_TLP/Views/Conta/Registro2.cshtml
@model PROJECTO_TLP.Models.RegisterViewModel
@{
    ViewBag.Title = "Criar nova conta";
}

<style>
    #main-registrar {
        margin: auto;
        padding: 2vh 2vh 5vh 2vh;
        background-color: #fff;
        max-width: 800px;
        box-shadow: 0 0 10px #dfdfdf;
    }

    .control-label {
        font-size: 2.2vh;
    }

    #aside {
        max-width: 800px;
        margin: auto;
        background-color: #cbd7fa;
        color: #404040;
        box-shadow: 0 0 2px silver;
        padding: 2vh 5vh 5vh 5vh;
        margin-bottom: 10px;
        display: flex;
        flex-direction: column;
        gap: 1.5rem;
    }
</style>


<div id="div-registro">


    <main id="main-registrar" class="container row">
        <aside id="aside" class="container row" role="complementary">
            <h1 style="font-size:40px">Congregação <span class="text-primary">Combal-18</span> </h1>
            <h1>Relatório de serviço de campo</h1>
        </aside>

        <h2>@ViewBag.Title.</h2>
        <h3>Informacoes adicionais</h3>
        <hr />


        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="form-group row">
            <div class=" col-md-5"><label for="div-nasc" class="control-label">Data de nascimento</label></div>
            <div class="col-md-7"><input type="date" id="div-nasc" class="form-control" required /></div>
        </div>

        <div class="form-group row">
            <div class=" col-md-5"><label for="div-batismo" class="control-label">Data de batismo</label></div>
            <div class="col-md-7"><input type="date" id="div-batismo" class="form-control" required /></div>
        </div>

        <div class="" style="color:red;font-size:2.2vh">
            Se for batizado!!
        </div>

        <hr />
        <h3>Servico na congregacao</h3>
        <div class="form-group row">
            <div class=" col-md-12">
                <label for="label-anciao" class="control-label col-xs-4">Anciao</label>
                <input class="" type="checkbox" id="label-anciao" />
            </div>
            <div class=" col-md-12">
                <label for="label-servo" class="control-label col-xs-4">Servo ministerial</label>
                <input class="" type="checkbox" id="label-servo" />
            </div>
            <div class=" col-md-12">
                <label for="label-anciao" class="control-label col-xs-4">Pioneiro regular, especial ou missioanario</label>
                <input class="" type="checkbox" id="label-anciao" />
            </div>

        </div>


        <div style="display:flex;width:100%;column-gap:5vh;justify-content:flex-start;flex-wrap:wrap">
            <div class="row col-md-offset-0" style="width:150%;padding:0 0 10px 0">
                <div class="col-md-12 text-success" style="font-size:2.5vh">
                    Confirme as informacoes!
                </div>
            </div>
            @*<a id="btn-confirmar" onclick="" role="button" class="btn btn-primary" style="width:100%;height:40px" @Html.ActionLink("Confirmar Registro","ConfirmarRegistro","EsqueceuPasse") </a>*@

            @*@Html.Action("ConfirmarRegistro","EsqueceuPasse")*@
        </div>
        <div class="btn-group col-md-6">
            <a style="height:40px;font-size:2.5vh" class="btn btn-success col-md-6" @Html.ActionLink("Confirmar Registro", "ConfirmarRegistro", "Conta") </a>
            <a style="height:40px;font-size:2.5vh" class="btn col-md-6 btn-warning" @Html.ActionLink("Voltar", "Registro", "Conta")  </a>
        </div>

    </main>

</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}